// Code generated by github.com/gobuffalo/packr. DO NOT EDIT

package config

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("./templates", "settings.yaml.tmpl", "\"dmVyc2lvbjoge3suVmVyc2lvbn19\"")
		packr.PackJSONBytes("./templates", "test.tmpl", "\"aGVsbG8=\"")
}
